-- AlterTable
ALTER TABLE `notifications` MODIFY `type` ENUM('DOCUMENT_UPLOADED', 'BALLOT_OPENED', 'BALLOT_CLOSED', 'MEETING_CREATED', 'MEETING_UPDATED', 'MEETING_CANCELLED', 'MEETING_REMINDER', 'ANNOUNCEMENT_CREATED') NOT NULL;
